#!/bin/sh

export PATH="$PATH:/C/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/C/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0C:/Program Files (x86)/MSBuild/14.0/bin:/C/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDEC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN:/C/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/Tools:/C/Windows/Microsoft.NET/Framework/v4.0.30319:/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC/VCPackages:/C/Program Files (x86)/HTML Help Workshop:/C/Program Files (x86)/Microsoft Visual Studio 14.0/Team Tools/Performance Tools:/C/Program Files (x86)/Windows Kits/10/bin/x86:/C/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 ToolsC:/Program Files (x86)/Common Files/Oracle/Java/javapath:/C/Windows/system32:/C/Windows:/C/Windows/System32/Wbem:/C/Windows/System32/WindowsPowerShell/v1.0C:/Windows/System32/OpenSSHC:/Program Files/doxygen/bin:/C/Program Files/Git/cmd:/C/Users/Coral/AppData/Local/Android/Sdk/tools:/C/Users/Coral/AppData/Local/Android/Sdk/platform-tools:/C/Qt/5.9.1/msvc2015/bin:/C/Windows/system32/config/systemprofile/.dnx/bin:/C/Program Files/Microsoft DNX/DnvmC:/Program Files/Microsoft SQL Server/130/Tools/BinnC:/Users/Coral/AppData/Local/Android/Sdk/ndk-bundle/build:/C/Users/Coral/AppData/Local/bin/NASM:/C/Users/Coral/Downloads:/C/Program Files (x86)/Windows Kits/8.1/Windows Performance ToolkitC:/Python27:/C/Program Files/dotnetC:/MinGW/bin:/C/Program Files/CMake/bin:/C/Program Files/Microsoft SQL Server/120/Tools/BinnC:/Users/Coral/AppData/Local/Microsoft/WindowsApps:/C/Users/Coral/AppData/Local/Android/Sdk/platform-tools:/C/Users/Coral/AppData/Local/Android/Sdk/tools:/C/Qt/5.9.1/msvc2015/bin:/C/Users/Coral/AppData/Local/Android/Sdk/ndk-bundle:/C/Python27C:/Python27/ScriptsC:/MinGW/bin: 
:/C/Users/Coral/Desktop/CoralPhone-desktop/WORK/desktop/cmake/programs"
export INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt; 
"
export LIB="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86; 
"
export LIBPATH="C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral; 
"

cd C:/Users/Coral/Desktop/CoralPhone-desktop/linphone-sdk/external/libvpx
make V=1 2>&1 >> "C:/Users/Coral/Desktop/CoralPhone-desktop/WORK/desktop/cmake/EP_vpx.log"
